name: Publish Haseroz.DevKit.AspNetCore

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Get version from tag
      id: get_version
      run: echo "##[set-output name=VERSION;]${GITHUB_REF#refs/tags/v}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish Haseroz.DevKit.AspNetCore
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        rm -rf ./nupkg/
        dotnet pack --no-build --configuration Release /p:Version=${{ env.VERSION }} --output ./nupkg
        dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
